-- AlterTable
ALTER TABLE "GasConsumption" ALTER COLUMN "reading" DROP DEFAULT,
ALTER COLUMN "reading" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "WaterConsumption" ALTER COLUMN "reading" DROP DEFAULT,
ALTER COLUMN "reading" SET DATA TYPE DOUBLE PRECISION;
